# Módulo 1: Espacios vectoriales con producto interno.
## Tema 1: Espacios vectoriales.
### Laboratorio 03: Solución de Sistemas de Ecuaciones Lineales (SEL) con NumPy.
Las funciones de álgebra lineal de NumPy proporcionan implementaciones eficientes de algoritmos de álgebra lineal; el submódulo `linang` proporciona algunas funciones muy útiles para la solución de sistemas de ecuaciones, además de que el objeto *ndarray* simplifica el cálculo de las operaciones elementales. A continuación se presentan algunos ejemplos que ilustran el trabajo con sistemas de ecuaciones lineales.

In [ ]:
# Para importar las librerías, suele utilizarse el sobrenombre **np**.
import numpy as np
# linalg es la parte de la librería Numpy con funciones para trabajo con álgebra lineal
import numpy.linalg as npl

## Solución general de un sistema de ecuaciones lineales no homogéneo.
La solución general del SEL es una expresión que permitirá generar al conjunto solución.

> **Teorema**.
Sea $A\boldsymbol{x} = \boldsymbol{b}$ un SEL no homogéneo. La solución general $\boldsymbol{x}$ está dada por $$\boldsymbol{x}=\boldsymbol{x}_p + \boldsymbol{x}_c$$ donde $\boldsymbol{x}_p$ es una solución particular del SEL y $\boldsymbol{x}_c$ es la solución del sistema homogéneo $A\boldsymbol{x} = \boldsymbol{0}$.






## Algoritmo de Gauss - Jordan.
Dado un SEL en su representación matricial, la *reducción gaussiana* se realiza por medio de la aplicación sucesiva de tres operaciones elementales (es decir, que se realizan entre los elementos de la matriz) y permiten transformar la representación matricial del sistema de ecuaciones en una forma más simple, pero preservando la solución.

- **Intercambiar renglones**: representa simplemente un intercambio en el orden en que aparecen las ecuaciones del sistema.
- **Multiplicar un renglón por un escalar**: esto implica obtener un múltiplo de la recta (plano o hiperplano) representada por la ecuación de dicho renglón, que gráficamente consiste en la misma recta (plano o hiperplano).
- **Sumar un múltiplo de un renglón a otro renglón**: es claro que esta operación consiste en sumar un múltiplo de una ecuación a otra, siendo la operación básica del método de suma y resta para reducir la dimensión.

El algoritmo inicia localizando seleccionando como `pivote` al primer elemento del primer renglón ($a_{11}$), siendo este el renglón actual. Luego, se siguen estos pasos:
1. Si `pivote` = 0, intercambiar el renglón actual por el primero que no tenga un 0 en la columna del pivote (en caso de que la columna actual).
2. Obtener un múltiplo adecuado del renglón actual para sumárselo a cada uno de los renglones debajo de éste y hasta el último, para introducir 0 debajo del `pivote` (esta operación no implica afectar el renglón actual).
3. Pasar al siguiente renglón para hacerlo el nuevo renglón actual.
4. Repetir desde el paso 1 mientras exista un `pivote`.

### Ejemplo 1.
Considérese el siguiente sistema de ecuaciones
$$\begin{array}{rll}
-2x_1+4x_2-2x_3-x_4+4x_5&=-3\\
4x_1-8x_2+3x_3-3x_4+x_5&=2\\
x_1-2x_2+x_3-x_4+x_5&=0\\
x_1-2x_2-3x_4+4x_5&=-1
\end{array}$$
Hallar el conjunto solución.

*Solución*. Primero se escribe en su forma matricial $A\boldsymbol{x}=\boldsymbol{b}$, construyendo la matriz aumentada $[A |\boldsymbol{b}]$:

$$\begin{bmatrix}
-2&4&-2&-1&4&-3\\
4&-8&3&-3&1&2\\
1&-2&1&-1&1&0\\
1&-2&0&-3&4&-1\end{bmatrix}$$


In [ ]:
# Construir la matriz aumentada
A = np.vstack([[-2,4,-2,-1,4],[4,-8,3,-3,1],[1,-2,1,-1,1],[1,-2,0,-3,4]])
b = np.vstack([-3,2,0,-1])

# Ab es la matriz aumentada:
Ab = np.hstack([A,b])
print(Ab)

En este caso, convene intercambiar los renglones 1 y 3 para introducir un `pivote` = 1:

$$\begin{bmatrix}
-2&4&-2&-1&4&-3\\
4&-8&3&-3&1&2\\
1&-2&1&-1&1&0\\
1&-2&0&-3&4&-1\end{bmatrix}\begin{array}{rll}\text{Intercambiar con }R_3\\\\\text{Intercambiar con }R_1\\\\\end{array}$$

El intercambio de renglones en un *ndarray* se puede hacer directamente, sin necesidad de visitar todos los elementos de cada fila involucrada:


In [ ]:
# Intercambiar los renglones R1 con R3
Ab[[0,2]] = Ab[[2,0]]
print(Ab)

Ahora, se introducen 0 debajo del pivote. Para esto, es necesario aplicar las siguientes transformaciones elementales:
$$\begin{bmatrix}
1&-2&1&-1&1&0\\
4&-8&3&-3&1&2\\
-2&4&-2&-1&4&-3\\
1&-2&0&-3&4&-1\end{bmatrix}\begin{array}{lll}\\-4R_1\\+2R_1\\-R_1\\\end{array}$$

In [ ]:
# Aplicando las transformaciones elementales en el renglon 2,3,4
Ab[1] += -4*Ab[0]  # Renglon 2
# Ab[1] = Ab[1]+ -4*Ab[0]
Ab[2] += 2*Ab[0]  # Renglon 3
Ab[3] += -Ab[0]    # Renglon 4
print(Ab)

La matriz que resulta es
\begin{bmatrix}
1&-2&1&-1&1&0\\
0&0&-1&1&-3&2\\
0&0&0&-3&6&-3\\
0&0&-1&-2&3&-1\end{bmatrix}

Notemos que la segunda columna no tiene pivote; así, se toma el elemento $Ab_{23}$ para introducir 0 debajo realizando la operación:
$$\begin{bmatrix}
1&-2&1&-1&1&0\\
0&0&-1&1&-3&2\\
0&0&0&-3&6&-3\\
0&0&-1&-2&3&-1\end{bmatrix}\begin{array}{lll}\\\\\\-R_2+R_4\\\end{array}$$

In [ ]:
# Recordar que las posiciones en los arreglos inician en 0
Ab[3] += -Ab[1]  #-R2+R4
print(Ab)

De la matriz que resulta, convertimos en 1 el pivote del renglón actual y el del renglón siguiente, ubicado en la posición $Ab_{34}$.


Aplicando las operaciones:
$$\\
\rightsquigarrow\begin{bmatrix}
1&-2&1&-1&1&0\\
0&0&-1&1&-3&2\\
0&0&0&-3&6&-3\\
0&0&0&-3&6&-3\end{bmatrix}\begin{array}{lll}\\\cdot(-1)\\\cdot(-\frac{1}{3})\\\\\end{array}\\
$$

In [ ]:
# Aplicando la operación elemental:
Ab[1] *= -1    # -1*R2

# Convertir la matriz a flotante, pues se hará una división
Ab = Ab.astype(float)

Ab[2] *= -(1/3)  # R2*(-1/3)

print(Ab)

A la matriz que se obtiene, se le aplica la siguiente operación elemental:
$$\\
\rightsquigarrow\begin{bmatrix}
1&-2&1&-1&1&0\\
0&0&1&-1&3&-2\\
0&0&0&1&-2&1\\
0&0&0&-3&6&-3\end{bmatrix}\begin{array}{lll}\\\\\\3R_3+R_4\\\end{array}$$

In [ ]:
# Operación elemental 3R3+R4
Ab[3] += 3*Ab[2]
print(Ab)

para obtener, finalmente, la matriz
$$\rightsquigarrow\begin{bmatrix}
1&-2&1&-1&1&0\\
0&0&1&-1&3&-2\\
0&0&0&1&-2&1\\
0&0&0&0&0&0\end{bmatrix}$$
La matriz aumentada se encuentra ahora en su *forma escalonada por renglones*. Regresando a la notacion original, esta matriz representa:
$$\begin{array}{rll}
x_1-2x_2+x_3-x_4+x_5&=0\\
x_3-x_4+3x_5&=-2\\
x_4-2x_5&=1\\
0&=0
\end{array}$$
Es claro entonces que el sistema tiene infinitas soluciones; la segunda y la última incógnita $x_2$ y $x_5$ son libres y se parametrizan. Notemos que, por ejemplo, si $x_2 = x_5 =0$, entonces, una solucion particular $\textbf{x}_p$ es
$$\textbf{x}_p=\begin{bmatrix}x_1\\x_2\\x_3\\x_4\\x_5\end{bmatrix}=\begin{bmatrix}2\\0\\-1\\1\\0\end{bmatrix}$$

In [ ]:
# La solución particular xp:
sol_particular = np.vstack([2,0,-1,1,0])


# Verificar que efectivamente es solución:Si el vector sol_particular resuelve el sistema no homogéneo, al multiplicar por la matriz A, deberá resultar en el vector b
print(np.dot(A,sol_particular))
print(b)

Ahora, para completar la solución general, encontramos la solución $\boldsymbol{x}_c$ del sistema homogéneo afín $A\boldsymbol{x} = \boldsymbol{0}$. Para esto, no debemos perder de vista que la única diferencia entre ambos está en la parte aumentada de la matriz, que en el caso de este segundo está formada totalmente por 0; esto implica que se realizan las mismas operaciones elementales que hemos realizado ya.

Así, el SEL homogéneo afín corresponde hasta ahora a
$$\begin{array}{rll}
x_1-2x_2+x_3-x_4+x_5&=0\\
x_3-x_4+3x_5&=0\\
x_4-2x_5&=0\\
0&=0
\end{array}$$ o bien,
$$\begin{bmatrix}
1&-2&1&-1&1&0\\
0&0&1&-1&3&0\\
0&0&0&1&-2&0\\
0&0&0&0&0&0\end{bmatrix}$$

In [ ]:
# La matriz aumentada del sistema homogeneo:
Ab_h = np.copy(Ab[:,:5])

Ab_h = np.hstack([Ab_h,np.zeros((4,1))])
Ab_h

Finalmente, bastará con convertir en 0 los elementos sobre cada pivote para llevar la matriz a su forma escalonada reducida:
$$\begin{bmatrix}
1&-2&1&-1&1&0\\
0&0&1&-1&3&0\\
0&0&0&1&-2&0\\
0&0&0&0&0&0\end{bmatrix}\begin{array}{lll}
\\
-R_2+R_1\\
\\
\\
\end{array}$$

In [ ]:
# Convertir en 0 los elementos sobre los pivotes:
# -R2+R1
Ab_h[0] += -Ab_h[1]
print(Ab_h)

y por último
$$
\rightsquigarrow\begin{bmatrix}
1&-2&0&0&-2&0\\
0&0&1&-1&3&0\\
0&0&0&1&-2&0\\
0&0&0&0&0&0\end{bmatrix}\begin{array}{lll}
\\
R_3+R_2\\
\\
\\
\end{array}$$



In [ ]:
#R3+R2
Ab_h[1] += Ab_h[2]

Ab_h

de donde se tiene la matriz $$\begin{bmatrix}
1&-2&0&0&-2&0\\
0&0&1&0&1&0\\
0&0&0&1&-2&0\\
0&0&0&0&0&0\end{bmatrix}$$

Las columnas con pivote son $\textbf{c}_1$, $\textbf{c}_3$ y $\textbf{c}_4$  y las columnas $\textbf{c}_2$ y $\textbf{c}_5$ pueden escribirse en términos de ellas: es claro que $$\textbf{c}_2 = -2 \textbf{c}_1$$ de donde se sigue que , $$2 \textbf{c}_1 + \textbf{c}_2 = \textbf{0}$$

Además, $$\textbf{c}_5=-2\textbf{c}_1+\textbf{c}_3-2\textbf{c}_4$$ o bien, $$-2\textbf{c}_1+\textbf{c}_3-2\textbf{c}_4-\textbf{c}_5=\textbf{0}$$

de modo que los vectores
$$\begin{bmatrix}2\\1\\0\\0\\0\end{bmatrix} \text{ y } \begin{bmatrix}-2\\0\\1\\-2\\-1\end{bmatrix}$$ son soluciones del sistema homogéneo, como cualquier combinación lineal de ellos. Así, la solución $$\boldsymbol{x}_c = k_1 \begin{bmatrix}2\\1\\0\\0\\0\end{bmatrix} + k_2 \begin{bmatrix}-2\\0\\1\\-2\\-1\end{bmatrix}$$ es la solución general del SEL homogéneo afín

In [ ]:
# Las soluciones del sistema homogéneo afín:
sol_homogenea1 = np.vstack([2,1,0,0,0])
sol_homogenea2 = np.vstack([-2,0,1,-2,-1])


# Verificar que efectivamente son soluciones: si la combinación lineal de los vectores sol_homogenea1 y 2 resuelve el sistema homogéneo, al multiplicar por la matriz A, deberá resultar en el vector 0
k1 = int(input("introduce un escalar k1:"))
k2 = int(input("introduce un escalar k2:"))
print(np.dot( A, k1*sol_homogenea1 + k2*sol_homogenea2 ))


Por tanto,
$$\left\{\textbf{x}\in\mathbb{R}^5:\textbf{x}=\begin{bmatrix}2\\0\\-1\\1\\0\end{bmatrix}+k_1\begin{bmatrix}2\\1\\0\\0\\0\end{bmatrix}+k_2\begin{bmatrix}-2\\0\\1\\-2\\-1\end{bmatrix}, k_1,k_2\in\mathbb{R}\right\}$$
es el conjunto solución que buscábamos.


In [ ]:
sol_gral = sol_particular + k1*sol_homogenea1 +k2*sol_homogenea2

# El producto de la matriz de coeficientes A con el vector solucion sol con los valores de las incógnitas x, debe ser igual a b
bsol = np.dot(A,sol_gral)
print("el vector ",sol_gral,"Satisface la ecuación: ",bsol)

## La función `solve()`.

La función `solve()` del submódulo `numpy.linalg` se utiliza para resolver sistemas de ecuaciones lineales de la forma $A\boldsymbol{x}=\boldsymbol{b}$
donde:
- $A\in \mathbb{R}^{n \times n}$ es una matriz cuadrada *invertible*. Esto implica que sólo aplica cuando el SEL tiene solución única.
- $\boldsymbol{b}$ es un vector columna de $n$ elementos y
- $\boldsymbol{x}$ es el vector incógnita que `solve()` encuentra.

Su sintaxis es `linalg.solve([a], [b])`:
- Parámetros:
  - `[a]`: La matriz de coeficientes.
  - `[b]`: El vector con los términos independientes de cada ecuación.
- Devuelve:
  - `x`. El arreglo (un objeto *ndarray*)  con la solución del sistema $A\boldsymbol{x} = \boldsymbol{b}$. La dimensión del arreglo es idéntica a la del vector $\boldsymbol{b}$.

- Excepciones:
  - Excepción del tipo *LinAlgError*: si la matriz es singular o no cuadrada


### Ejemplo 2.
 Resolver el sistema
 $$\begin{array}{rll}x_1&+&x_2&+&x_3&=&3\\x_1&-&x_2&+&2x_3&=&2\\&&x_2&+&x_3&=&2\end{array}$$

*Solución*. Para resolverlo, formamos la *matriz aumentada* del SEL con la matriz de coeficientes y el vector $\boldsymbol{b}$ de tériminos independientes:

In [ ]:
# Creación de las matrices:
A = np.vstack([[1,1,1],[1,-1,2],[0,1,1]])
b = np.vstack([3,2,2])

# Imprimie la matriz aumentada
print(np.hstack([A,b]))

# Llamada a la función solve()
print("La solucion es")
npl.solve(A,b)

### Ejemplo 3.
Resolver sistemas de ecuaciones:

$$\begin{array}{rll}x_1&+&x_2&+&x_3&=&3\\x_1&-&x_2&+&2x_3&=&2\\2x_1&&&+&3x_3&=&1\end{array}$$

*Solución*. Cuando el SEL no tiene solución única, la función `solve()` lanza una excepción:

In [ ]:
# Definición de las matrices:
A = np.vstack([[1,1,1],[1,-1,2],[2,0,3]])
b = np.vstack([3,2,1])
print(np.hstack([A,b]))


# solve: resuelve un sistema de ecuaciones con la matriz A y la parte aumentada
try:
  npl.solve(A,b)
except:
  print(np.hstack([A,b]))
  print("No tiene solución única")

# si el sistema no tiene solución, el comando solve devuelve una excepción.

# Ejercicios.

### Ejercicio 1. Escribe el código necesario para resolver el sistema de ecuaciones:
\begin{array}{c}
x_{1}+x_{2}+2x_{3}=8\\
-x_{1}-2x_{2}+3x_{3}=1\\
3x_{1}-7x_{2}+4x_{3}=10
\end{array}


**Escribe tu código debidamente comentado, explicando tus procedimientos.**


In [ ]:
# Escribe tu código aquí:

# Creación de las matrices:
A = np.vstack([[1,1,2],[-1,-2,3],[3,-7,4]])
B = np.vstack([8,1,10])

# Imprimie la matriz aumentada
print(np.hstack([A,B]))

# Resolver el sistema de ecuaciones
solucion = np.linalg.solve(A,B)

# Imprimir la solución del sistema
print ('La solución es:')
print (solucion)

# Calculo de A * X = B
print('A * x = ')
print (np.dot(A,solucion))
print('B = ')
print (B)

### Ejercicio 2. Escribe el código necesario para resolver el sistema de ecuaciones:
\begin{array}{c}
2x_{1}+2x_{2}+2x_{3}=0\\
-2x_{1}+5x_{2}+2x_{3}=1\\
8x_{1}+x_{2}+4x_{3}=-1
\end{array}


Por medio de la reducción de Gauss - Jordan, aplicando las operaciones elementales.
**Escribe tu código debidamente comentado, explicando tus procedimientos.**


In [67]:
# Escribe tu código aquí:
A = np.vstack([[2, 2, 2], [-2, 5, 2], [8, 1, 4]])
b = np.vstack([0, 1, -1])

# Escribe la matriz aumentada:
Ab = np.hstack([A, b]).astype(float)

print(Ab)

[[ 2.  2.  2.  0.]
 [-2.  5.  2.  1.]
 [ 8.  1.  4. -1.]]


Reduciendo la matriz a su forma escalonada:

In [68]:
# Convertir el primer pivote en 1.
# Multiplicar por 1/2 todo el primer renglón
Ab[0] = (1/2) * Ab[0]
print(Ab)
print('\n')
# Convertir en 0 los elementos debajo del pivote:
# 2*R1+R2
Ab[1] += 2 * Ab[0]
print(Ab)
print('\n')
# -8*R1+R3
Ab[2] += -8 * Ab[0]
print(Ab)

[[ 1.  1.  1.  0.]
 [-2.  5.  2.  1.]
 [ 8.  1.  4. -1.]]


[[ 1.  1.  1.  0.]
 [ 0.  7.  4.  1.]
 [ 8.  1.  4. -1.]]


[[ 1.  1.  1.  0.]
 [ 0.  7.  4.  1.]
 [ 0. -7. -4. -1.]]


In [69]:
# El siguiente pivote se convierte en 1:
# (1/7)R2
Ab[1] = (1/7) * Ab[1]
print (Ab)
print('\n')

# Convertir el elemento bajo el pivote en 0:
# 7*R2+R3
Ab[2] += 7 * Ab[1]
print (Ab)
print('\n')

# Convertir el elemento sobre el pivote en 0:
# -1*R1+R2 (para hacer 0 el elemento en posición [0,1])
Ab[0] += -1 * Ab[1]
print(Ab)

[[ 1.          1.          1.          0.        ]
 [ 0.          1.          0.57142857  0.14285714]
 [ 0.         -7.         -4.         -1.        ]]


[[1.         1.         1.         0.        ]
 [0.         1.         0.57142857 0.14285714]
 [0.         0.         0.         0.        ]]


[[ 1.          0.          0.42857143 -0.14285714]
 [ 0.          1.          0.57142857  0.14285714]
 [ 0.          0.          0.          0.        ]]


La matriz en su forma escalonada reducida es
\begin{bmatrix}
1&0&\frac{3}{7}&-\frac{1}{7}\\
0&1&\frac{4}{7}&\frac{1}{7}\\
0&0&0&0
\end{bmatrix}
por lo tanto, el sistema tiene infinitas soluciones. Estas pueden generarse si encontramos una solución particular $\boldsymbol{x}_p$ a la cual podamos sumar un **0** expresado de manera conveniente, es decir la solución $\boldsymbol{x}_c$ del sistema homogéneo $A \boldsymbol{x}=\boldsymbol{0}$ asociado, como indica el Teorema enunciado anteriormente.

Para la solución particular $\boldsymbol{x}_p$, notemos que la matriz en su forma escalonada reducida representa a las ecuaciones
\begin{array}{c}
x_{1}+\frac{3}{7}x_{3}=-\frac{1}{7}\\
x_{2}+\frac{4}{7}x_{3}=\frac{1}{7}\\
0=0
\end{array}
por lo que es claro que si particularmente $ x_{3}=0$, entonces $\boldsymbol{x}_{p}=\left (-\frac{1}{7}, \frac{1}{7}, 0 \right )^T$ es una solución particular del sistema.


In [70]:
# Definición de la solución particular xp:
# De la matriz escalonada reducida, fijamos x3 = 0
# Esto nos da: x1 = -1/7, x2 = 1/7, x3 = 0
xp = np.vstack([-1/7, 1/7, 0])

# Verificar que es solución particular del SEL:
# Para ser solución, debe cumplirse: A · xp = b
resultado = np.dot(A, xp)

print("Verificación de la solución particular")
print("A · xp = ")
print(resultado,'\n')
print("     b = ")
print(b, '\n')

Verificación de la solución particular
A · xp = 
[[ 0.]
 [ 1.]
 [-1.]] 

     b = 
[[ 0]
 [ 1]
 [-1]] 




Para la solución general $\boldsymbol{x}_c$ del SEL homogéneo $A\boldsymbol{x}=\boldsymbol{0}$ notemos que la tercera columna puede escribirse en términos de las primeras dos:
$$\textbf{c}_3 = \frac{3}{7}\textbf{c}_1 + \frac{4}{7}\textbf{c}_2$$
por lo que es claro que
$$\frac{3}{7}\textbf{c}_1 + \frac{4}{7}\textbf{c}_2-\textbf{c}_3 = \boldsymbol{0}$$
así $\boldsymbol{x}_c = \left( \frac{3}{7}, \frac{4}{7}, -1 \right )^T$ es una solución del sistema homogéneo.

In [71]:
# Definición de la solución xc del sistema homogéneo Ax=0
# De la matriz reducida: x1 = -3/7*x3, x2 = -4/7*x3
# Si x3 = -1, entonces xc = [3/7, 4/7, -1]
xc = np.vstack([3/7, 4/7, -1])
print('A = ')
print(A)
print('xc = ')
print(xc)
# Verificar que es solución del sistema homogéneo:
print('A * xc = \n', np.round(np.dot(A, xc)))

A = 
[[ 2  2  2]
 [-2  5  2]
 [ 8  1  4]]
xc = 
[[ 0.42857143]
 [ 0.57142857]
 [-1.        ]]
A * xc = 
 [[ 0.]
 [-0.]
 [ 0.]]


y por tanto, la solución general del sistema está dada por

$$
\left\{
  \textbf{x}\in\mathbb{R}^5:\textbf{x}=
  \begin{bmatrix}
  -\frac{1}{7}\\\frac{1}{7}\\0
  \end{bmatrix}
  +k_1
  \begin{bmatrix}
  \frac{3}{7}\\\frac{4}{7}\\-1
  \end{bmatrix};
  k_1 \in\mathbb{R}
  \right\}
$$


In [72]:
# Definición de la solución general:
# El escalar k1:
k1 = float(input("Introduce un valor para k1: "))

sgral = xp + xc

# Imprimir en forma de vector renglón usando .flatten()
print("xp (particular)  = ")
print(xp)
print("xc (homogénea)   = ")
print(xc)
print("k1               = ")
print(k1)
print("x_general        = ")
print(sgral)

# Verificar que este vector es solución general del sistema: A · x = b
resultado = np.dot(A, sgral)

print("A · x_general = ")
print(resultado)
print("b             = ")
print(b)

Introduce un valor para k1: 5
xp (particular)  = 
[[-0.14285714]
 [ 0.14285714]
 [ 0.        ]]
xc (homogénea)   = 
[[ 0.42857143]
 [ 0.57142857]
 [-1.        ]]
k1               = 
5.0
x_general        = 
[[ 0.28571429]
 [ 0.71428571]
 [-1.        ]]
A · x_general = 
[[-2.22044605e-16]
 [ 1.00000000e+00]
 [-1.00000000e+00]]
b             = 
[[ 0]
 [ 1]
 [-1]]


### Ejercicio 3.  Escribe el código necesario para resolver el sistema de ecuaciones:
\begin{array}{c}
2x_{1}+x_{2}+3x_{3}=0\\
x_{1}+2x_{2}=0\\
x_{2}+x_{3}=0
\end{array}
Encuentra el conjunto solución.

**Escribe tu código debidamente comentado, explicando tus procedimientos.**


In [ ]:
# Escribe tu código aquí:
A = np.vstack([[2, 1, 3], [1, 2, 0], [0, 1, 1]])
B = np.vstack([0, 0, 0])

# Escribe la matriz aumentada:
AB = np.hstack([A, B])
print("Matriz aumentada:")
print(AB)

#Resolver el sistema
solucion = np.linalg.solve(A, B)

#Imprimir el conjunto solución
print('Conjunto solución:')
print (solucion)


### Ejercicio 4.  Escribe el código necesario para resolver el sistema de ecuaciones:
\begin{array}{c}
-x_{1}-4x_{2}+2x_{3}+x_{4}=-32\\
2x_{1}-x_{2}+7x_{3}+9x_{4}=14\\
-x_{1}+x_{2}+3x_{3}+x_{4}=11\\
x_{1}-2x_{2}+x_{3}-4x_{4}=-4
\end{array}

**Escribe tu código debidamente comentado, explicando tus procedimientos.**

In [73]:
# Escribe tu código aquí:
A = np.vstack([[-1, -4, 2, 1], [2, -1, 7, 9], [-1, 1, 3, 1], [1, -2, 1, -4]])
B = np.vstack([-32, 14, 11, -4])

# Escribe la matriz aumentada:
AB = np.hstack([A, B])
print("Matriz aumentada:")
print(AB)

# Resolver el sistema de ecuaciones
solucion = np.linalg.solve(A, B)

# Imprimir el conjunto solución
print('La solución es:')
print(solucion)


Matriz aumentada:
[[ -1  -4   2   1 -32]
 [  2  -1   7   9  14]
 [ -1   1   3   1  11]
 [  1  -2   1  -4  -4]]
La solución es:
[[ 5.]
 [ 8.]
 [ 3.]
 [-1.]]
