# Módulo 1: Espacios vectoriales con producto interno.
## Tema 1: Espacios vectoriales.
### Laboratorio 02 - Trabajo con matrices en *NumPy*.

*NumPy* es un proyecto open source que tiene como objetivo habilitar cómputo numérico con Python. El proyecto fue creado en 2005, construido sobre los trabajos previos de las librerías *Numeric* y *Numarray*.

Un submódulo interesante es *numpy*.***linalg*** que contiene funciones sobre álgebra lineal.

*Numpy* es una gran herramienta para la representación y manipulación de vectores, matrices y tensores. Como veremos, resultará mucho más eficiente trabajar con los objetos que implementa esta libreria que las estructuras de *Python*, como listas o tuplas.

In [1]:
# Para importar las librerías, suele utilizarse el sobrenombre **np**.
import numpy as np
# linalg es la parte de la librería Numpy con funciones para trabajo con álgebra lineal
import numpy.linalg as npl

#### Ejemplo 1. El objeto `numpy.ndarray` y funciones para trabajo con matrices.

*Python* no tiene un tipo de dato *matriz*, por lo que la alternativa consiste en interpretarla como una "*lista de listas*", por ejemplo:


In [2]:
A = [[1,2,3],[4,5,6]]
# Imprimir la lista de listas:
print(A)
#imprimir el renglón 1, completo:
print(A[1])
#imprimir el elemento en renglón 0, columna 1:
print(A[0][1])
type(A)

[[1, 2, 3], [4, 5, 6]]
[4, 5, 6]
2


list

Así, *NumPy* provee a *Python* del objeto **ndarray**, que es un *contenedor multidimensional* (generalmente de tamaño fijo) de elementos del mismo tipo y tamaño. El número de dimensiones y elementos de un *ndarray* se define por su *dimensión*, que es una tupla de $N$ enteros no negativos que especifican los tamaños de cada dimensión.

Al igual que con otros objetos contenedores en *Python*, se puede acceder y modificar el contenido de un *ndarray* indexando el arreglo y a través de los métodos y atributos del *ndarray*, que se encuentran detallados en la [documentación](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) de este objeto.

Es posible crear este tipo de arreglos multidimensionales con varias funciones de *NumPy*, entre las que se encuentran las siguientes.


**La función `array()`.**


`np.array([object], [dtype=None])`: crea un *ndarray*.
- Parámetros:
  - `object`: array_like. Un arreglo o un objeto cuyo método __array__ devuelva un arreglo.
  - `dtype`: data-type, opcional. Especifica el tipo de dato deseado para el arreglo. Si se omite, el tipo de dato será determinado
The desired data-type for the array. Si se omite, el tipo de dato se determinará como el tipo mínimo requerido para contener los objetos en la secuencia.
- Devuelve:
  - Un objeto *arreglo ndarray* que satisface los requerimientos especificados. Si el parámetro `[objet]` es un escalar, se devuelve una arreglo de dimensión 0 que contiene el objeto.




In [3]:
# Se despliega en esta forma para mejorar la visualización. Puede escribirse en una sola línea de código: B = np.array([[1,1,1],[1,-1,2],[2,0,3]])
B = np.array([
              [1,1,1],
              [1,-1,2],
              [2,0,3]
              ])
print(B)
type(B)


[[ 1  1  1]
 [ 1 -1  2]
 [ 2  0  3]]


numpy.ndarray

**La función `vstack()`**.


`numpy.vstack([tup])`: Apila arrays verticalmente (en forma de filas).

- Parámetros:
  - *tup*: secuencia de *ndarrays*. Los arreglos unidimensionales deben tener la misma longitud.
- Devuelve:
  - *stacked ndarray*. El arreglo formado apilando los arrays dados. Será de al menos 2-D.

In [4]:
# función vstack: Creación de una matriz 3x1. Cada componente que se apila es un escalar.
b = np.vstack([
               3,
               2,
               1
              ])
print(b)
type(b)

[[3]
 [2]
 [1]]


numpy.ndarray

In [5]:
# función vstack: Creación de una matriz 3x3. Cada componente que se apila es un arrays con la misma dimensión (horizontalmente).
A = np.vstack([
               [1,1,1],
               [1,-1,2],
               [2,0,3]
               ])
print(A)
type(A)

[[ 1  1  1]
 [ 1 -1  2]
 [ 2  0  3]]


numpy.ndarray

**La función `hstack()`.**

`numpy.hstack([tup])`: Apila los arreglos en secuencia horizontalmente (en columna).

- Parámetros:
  - *tup*: secuencia de *ndarrays*. Deben tener la misma dimensión verticalmente (la misma cantidad de renglones).
- Devuelve:
  - *stacked* ndarray. El arreglo formado apilando los arrays dados. Será de al menos 2-D.

In [6]:
# función hstack: Creación de una matriz 3x4. Se apilan las matrices A y b creadas en los pasos anteriores.
matriz_aumentada = np.hstack([A,b])
print(matriz_aumentada)
type(matriz_aumentada)

[[ 1  1  1  3]
 [ 1 -1  2  2]
 [ 2  0  3  1]]


numpy.ndarray

**Las funciones `zeros()` y `zeros_like()`.**

Con estas funciones es posible crear matrices de un tamaño específico, llenas de 0.

`np.zeros([shape], [dtype=float])` devuelve un nuevo array de la dimensión y tipo de dato especificados, lleno con ceros.

- Parametros:
  - **shape**: entero o tupla de enteros, con la dimensión del nuevo array; por ejemplo, 2, dará como resultado un arreglo unidimensional de dos componentes; o bien, (2, 3) dará una matriz de dos renglones y tres columnas.

  - **dtype**: data-type, *opcional*. El tipo de dato deseado para el arreglo; por ejemplo, el parámetro puede especificarse como *numpy.int8* para hacerlo de tipo entero. Si este parámetro no se especifica, por default es del tipo *numpy.float64*.

In [7]:
# zeros(): por default, se crea un arreglo de 2 espacios, flotante.

ceros_1_f = np.zeros(2)
print(ceros_1_f)

# zeros(): arreglo de 2 espacios, enteros.
ceros_1_i = np.zeros(2,int)
print(ceros_1_i)
# zeros(): arreglo de 2 espacios, complejos.
ceros_1_c = np.zeros(2,complex)
print(ceros_1_c)



[0. 0.]
[0 0]
[0.+0.j 0.+0.j]



`np.zeros_like([a],[dtype=None])` crea un array de ceros con la misma forma y tipo de dato que el array especificado.
- Parametros:
  - **a**: array_like. La forma y el tipo de dato del array definido aquí serán los mismos para el array devuelto.
  - **dtype**: data-type, *opcional*. Este parámetro anula el tipo de dato del array **a**, por lo que el tipo de dato del arreglo devuelto será el especificado aquí.

In [8]:
# Crear una matriz de ceros de 2-D con la misma dimensión que la matriz A
print (A)

# Creación de la matriz
ceros_2_d = np.zeros_like(A)
print(ceros_2_d)
print(type(ceros_2_d[0][0]))

# Creación de la matriz, pero en tipo de dato complejo:
ceros_2_c = np.zeros_like(A,complex)
print(ceros_2_c)
print(type(ceros_2_d[0][0]))


[[ 1  1  1]
 [ 1 -1  2]
 [ 2  0  3]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
<class 'numpy.int64'>
[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]
<class 'numpy.int64'>


#### Ejemplo 2. Operaciones entre arreglos y escalares.
Con un objeto *ndarray* de *Numpy* es posible realizar operaciones aritméticas entre escalares y los elementos del array, elemento a elemento. Los operadores que se utilizan son los estándar:
- sumar: +
- restar: -
- multiplicar: *
- dividir: /  
- dividir, con el cociente entero: //  
- potencia: **


In [9]:
# Operaciones con arrays:
arreglo_1 = np.vstack([[1,2,3],[4,5,6]])
print(arreglo_1)


# Sumar 1 a cada elemento del arreglo:
print(arreglo_1 + 1)

# Elevar cada elemento del arreglo al cuadrado:
print(arreglo_1**2 )

[[1 2 3]
 [4 5 6]]
[[2 3 4]
 [5 6 7]]
[[ 1  4  9]
 [16 25 36]]


**La función `add()`.**

Esta función suma arreglos elemento a elemento.


In [18]:
arreglo_1
arreglo_2 = np.vstack([[6,5,4],[3,2,1]])

# Escribe el código que suma los arreglos 1 y 2

resultado_suma = np.add(arreglo_1, arreglo_2)

print(resultado_suma)


[[7 7 7]
 [7 7 7]]


**La función `subtract()`.**

Esta función resta arreglos elemento a elemento.


In [19]:
print(arreglo_1)
print(arreglo_2)

# Escribe el código que resta los arreglos 1 y 2

resultado_resta = np.subtract(arreglo_1, arreglo_2)

print(resultado_resta)


[[1 2 3]
 [4 5 6]]
[[6 5 4]
 [3 2 1]]
[[-5 -3 -1]
 [ 1  3  5]]


**La función `multiply()`**

Recordar que el producto de matrices no se hace elemento a elemento, sino que tiene algunas consideraciones interesantes.


Si $A_{n\times r}$ y $B_{r\times m}$ son dos matrices, entonces el producto $AB_{m\times n}$ está definido.

*Numpy* tiene tres formas distintas de realizar el producto.

- La función `multiply()` realiza el producto de dos matrices del mismo tamaño, elemento por elemento. Evidentemente, no es el producto matricial.


In [20]:
print(arreglo_1)
print(arreglo_2)

# Escribe el código que aplica la función multiply: realiza el producto elemento por elemento.

resultado_mult = np.multiply(arreglo_1, arreglo_2)

print(resultado_mult)


[[1 2 3]
 [4 5 6]]
[[6 5 4]
 [3 2 1]]
[[ 6 10 12]
 [12 10  6]]


**La función `dot()`**.

La función `dot()` opera de varias maneras. Puede realizar el producto de un arreglo por un escalar, elemento por elemento, igual que hace el operador *.

In [21]:
# recordar que arreglo_1 es una matriz de 2x3
print(arreglo_1)

# Creación de arreglo_3. Es una matriz de 3x2
arreglo_3 = np.array([[1,2],[3,4],[4,5]])
print(arreglo_3)


# función dot: realiza el producto matricial siempre y cuando las dimensiones sean las adecuadas.
# Escribe el código que realiza el producto. El resultado es una matriz 2x2:

producto_dot = np.dot(arreglo_1, arreglo_3)
print("Producto con dot():\n", producto_dot)


[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [4 5]]
Producto con dot():
 [[19 25]
 [43 58]]


In [ ]:
# función dot: cuando las dimensiones no son adecuadas, lanza una excepción

# recordar que arreglo_1 y arreglo_2 son  matrices de 2x3
print(arreglo_1)
print(arreglo_2)
try:
  np.dot(arreglo_1,arreglo_2)
except:
  print("No puede realizarse el producto por la dimensión de las matrices")

**El operador `@`.**

Este operador funciona exactamente igual que la función `dot()` de *Numpy*.

In [ ]:
# Escribe el código que realiza producto de arreglo_1 (2x3) con arreglo_3 (3x2). El resultado es una matriz 2x2

producto_arroba = arreglo_1 @ arreglo_3
print("Producto con @:\n", producto_arroba)

#### Ejercicio 3. Producto matricial.
Calcular los productos de matrices $\textbf{AB} \ \text{y} \ \ \textbf{BA}$ con
$$\textbf{A}=\begin{bmatrix}1&2&3\\3&2&1\end{bmatrix}, \ \ \textbf{B}=\begin{bmatrix}0&2\\1&-1\\0&1\end{bmatrix}$$

In [24]:
# Definición de las matrices
A = np.array([[1,2,3],[3,2,1]])
B = np.array([[0,2],[1,-1],[0,1]])


In [25]:
# De manera alternativa utiliza ek operador @ para realizar el producto matricial

AB = A @ B
BA = B @ A

print("El producto AB es:\n", AB)
print("El producto BA es:\n", BA)


El producto AB es:
 [[2 3]
 [2 5]]
El producto BA es:
 [[ 6  4  2]
 [-2  0  2]
 [ 3  2  1]]


#### Ejercicio 4. Matriz Inversa.

Prueba que las matrices

$$\textbf{A}=\begin{bmatrix}1&2&1\\4&4&5\\6&7&7\end{bmatrix} \ \text{y} \ \textbf{B}=\begin{bmatrix}-7&-7&6\\2&1&-1\\4&5&-4\end{bmatrix}$$
son inversas de cada una, es decir, $\textbf{AB=I=BA}$.

In [26]:
# Definir las matrices

A = np.array([[1,4,6],[2,4,7],[1,5,7]])
B = np.array([[-7,2,4],[-7,1,5],[6,-1,-4]])

# Verificar que AB = I = BA
AB = A @ B
BA = B @ A
I = np.eye(3)

print("AB =\n", AB)
print("BA =\n", BA)


print("¿AB es identidad?", np.allclose(AB, I))
print("¿BA es identidad?", np.allclose(BA, I))

AB =
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
BA =
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
¿AB es identidad? True
¿BA es identidad? True
